#!/bin/bash
HERE="$(dirname "$(readlink -f "$0")")"
export PATH="${HERE}/python/bin:${PATH}"
export PYTHONHOME="${HERE}/python"
export LD_LIBRARY_PATH="${HERE}/python/lib:${LD_LIBRARY_PATH}"
export QT_QPA_PLATFORM_PLUGIN_PATH="${HERE}/python/lib/python3.11/site-packages/Qt6/plugins"
exec "${HERE}/python/bin/python3" "${HERE}/gui/main_gui.py" "$@"
